version: '2'
services:
  sepl-bpm:
    build: .
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - DB_NAME=camunda
      - GMAIL_USER=user@gmail.com
      - GMAIL_PW=password
    links:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DATABASE=camunda
    ports:
      - "5432:5432" 