version: '3'
services:
  senergy-bpm:
    build: .
    environment:
      # Set database configuration
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://db:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=camunda
      # Set credentials for smtp server
      - GMAIL_USER=user@gmail.com
      - GMAIL_PW=password
    links:
      - db
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DATABASE=camunda
    ports:
      - "5432:5432" 