name: 'PROD Docker Image'

on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: ".*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push arm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileARM
          platforms: linux/arm/v7
          push: true
          tags: |
            smartenergyplatform/process-engine:arm-prod
            ghcr.io/senergy-platform/process-engine:arm-prod
            smartenergyplatform/process-engine:arm-${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/senergy-platform/process-engine:arm-${{ steps.tag_version.outputs.new_tag }}
            smartenergyplatform/process-engine:arm-latest
            ghcr.io/senergy-platform/process-engine:arm-latest
      - name: Build and push amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileAmd
          platforms: linux/amd64
          push: true
          tags: |
            smartenergyplatform/process-engine:amd64-prod
            ghcr.io/senergy-platform/process-engine:amd64-prod
            smartenergyplatform/process-engine:amd64-${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/senergy-platform/process-engine:amd64-${{ steps.tag_version.outputs.new_tag }}
            smartenergyplatform/process-engine:amd64-latest
            ghcr.io/senergy-platform/process-engine:amd64-latest
      - name: Build and push multi
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          build-args: |
            VERSION=prod
          push: true
          tags: |
            smartenergyplatform/process-engine:prod
            ghcr.io/senergy-platform/process-engine:prod
            smartenergyplatform/process-engine:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/senergy-platform/process-engine:${{ steps.tag_version.outputs.new_tag }}
            smartenergyplatform/process-engine:latest
            ghcr.io/senergy-platform/process-engine:latest
