name: 'Tag Docker Image'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push arm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileARM
          platforms: linux/arm/v7
          push: true
          tags: |
            smartenergyplatform/process-engine:arm-${{ github.ref_name }}
            ghcr.io/senergy-platform/process-engine:arm-${{ github.ref_name }}
      - name: Build and push amd
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileAmd
          platforms: linux/amd64
          push: true
          tags: |
            smartenergyplatform/process-engine:amd64-${{ github.ref_name }}
            ghcr.io/senergy-platform/process-engine:amd64-${{ github.ref_name }}
      - name: Build and push multi
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7
          build-args: |
            VERSION=${{ github.ref_name }}
          push: true
          tags: |
            smartenergyplatform/process-engine:${{ github.ref_name }}
            ghcr.io/senergy-platform/process-engine:${{ github.ref_name }}